[package]
name = "daw_gui"
version.workspace = true
edition.workspace = true

[dependencies]
common = { path = "../common" }
anyhow.workspace = true
rfd.workspace = true
tokio.workspace = true
tracing.workspace = true
vizia.workspace = true

[target.'cfg(windows)'.dependencies]
windows.workspace = true
