[workspace]
resolver = "3"
members = ["common", "daw_gui", "daw_audio", "daw_plugin_host"]

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
anyhow = "1"
bincode = { version = "2", features = ["derive"] }
tokio = { version = "1", features = ["rt-multi-thread", "net", "macros", "io-util", "process"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }
