//! Build script for `ara-sys`.
//!
//! By default this does nothing but declare rerun triggers — normal builds use
//! the committed `src/bindings.rs` and require no libclang.
//!
//! With `--features regen` it regenerates `src/bindings.rs` from the vendored
//! ARA header via bindgen. This is a one-off developer step run on a win64 host:
//!
//! ```text
//! LIBCLANG_PATH=<dir containing libclang.dll> cargo build -p ara-sys --features regen
//! ```
//!
//! The win64 freestanding shim in `shim/` lets libclang parse `<stddef.h>` /
//! `<stdint.h>` without its resource headers, so no full LLVM install is needed.

fn main() {
    println!("cargo:rerun-if-changed=wrapper.h");
    println!("cargo:rerun-if-changed=vendor/ARA_API/ARAInterface.h");
    println!("cargo:rerun-if-changed=shim/stddef.h");
    println!("cargo:rerun-if-changed=shim/stdint.h");

    #[cfg(feature = "regen")]
    regen();
}

#[cfg(feature = "regen")]
fn regen() {
    // ARA is pure type definitions dispatched through plug-in-provided
    // function-pointer tables; there are no exported symbols to link.
    let bindings = bindgen::Builder::default()
        .header("wrapper.h")
        .clang_args(["-x", "c", "-std=c99", "-nostdinc", "-isystem", "shim"])
        .allowlist_type("ARA.*")
        .allowlist_var("(k|ARA)ARA.*")
        .allowlist_var("kARA.*")
        .allowlist_var("ARA.*")
        // ARA enums are 32-bit, value-typed identifiers; newtypes keep the type
        // distinction without UB on unknown discriminants (rustified enums are
        // unsound across an FFI boundary).
        .default_enum_style(bindgen::EnumVariation::NewType {
            is_bitfield: false,
            is_global: false,
        })
        // Emit size/align asserts so the 1-byte-packed ARA layout is verified
        // against the C ABI at `cargo test` time.
        .layout_tests(true)
        .raw_line("// @generated by `cargo build -p ara-sys --features regen` — do not edit by hand.")
        .raw_line("// Source: vendor/ARA_API/ARAInterface.h (ARA 2.3.0.001, Apache-2.0).")
        .generate()
        .expect("bindgen failed to generate ARA bindings");

    bindings
        .write_to_file("src/bindings.rs")
        .expect("failed to write src/bindings.rs");

    println!("cargo:warning=ara-sys: regenerated src/bindings.rs");
}
