# SPDX-FileCopyrightText: Copyright (C) 2026 Tahara Yoshinori
# SPDX-License-Identifier: GPL-3.0-or-later

[package]
name = "daw-ui-example-mixer"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[lints]
workspace = true

[[bin]]
name = "mixer"
path = "src/main.rs"

[dependencies]
daw-ui-platform.workspace = true
daw-ui-renderer.workspace = true
daw-ui-core.workspace = true
winit = "0.30.13"
