[package]
name = "daw_audio"
version.workspace = true
edition.workspace = true

[dependencies]
common = { path = "../common" }
anyhow.workspace = true
arc-swap.workspace = true
cpal.workspace = true
tokio.workspace = true
tracing.workspace = true

[target.'cfg(windows)'.dependencies]
windows.workspace = true
