#!/usr/bin/env python3
"""サイズ budget (不変条件 9) の測定器 — 物理行ではなく **実コード行 (ncloc)** で測る。

なぜ物理行では駄目なのか (実際に 2 回発火した逆インセンティブ)
--------------------------------------------------------------
不変条件 9 の判定は長らく `find … | xargs wc -l` の **物理行 3,000** だった。物理行は
テスト module も doc comment も同じ 1 行として課金するので、ゲートに近づいたとき
「テストを別ファイルへ移す」「doc を書かない」が最短の回避手段になる。構造は 1 ミリも
良くならないのに緑になる。実際にそういう commit が 2 件生えている:

  eefdea1  refactor(arch-refactor #9): model.rs god-file 分割 step1 — tests を model/tests.rs へ
           (-2270/+2476、本文「挙動・serialize 形式は不変 (pure code movement)」)
  720e2c1  refactor(arch-refactor #9): ui.rs god-file 分割 — tests を ui/tests.rs へ
           (本文「これで make arch-lint = OK (違反なし)」)

しかも物理行 3,000 という閾値は今日 **1 件も当たらない** (最大が
daw_audio/src/graph/compile.rs の 2,978 行)。その裏で
daw_gui/src/view/track_inspector/mod.rs:228 の `fn draw` が **実コード 2,063 行**まで
育っているのに、ファイルが 2,623 行なので一度も報告されていない。
検査が空振りしたまま真の god code を素通ししている、というのが r.md #76 の発見。

何を数えるか
------------
SonarQube の ncloc と同じ定義: **空白でもタブでもコメントの一部でもない文字を 1 つ以上
含む物理行**。doc comment (`///` `//!` `/** */` `/*!  */`) は comment 側に数える。
複数行にまたがる文字列リテラルの中身は code。閾値 1,000 は SonarQube の同種ルール
**S104 "Files should not have too many lines of code"** の既定値そのままで、SonarSource も
物理行から lines of code へ数え方を変えた経緯がある (sonar-dotnet#396 / MMF-571 /
"Kill the Noise")。同じ結論に業界の lint が先に到達している。

テストコードは budget の対象外 (上限を課さない)。不変条件 9 が防ぎたい故障は
「1 モジュールが無関係な責務を溜め込む」ことで、独立した `#[test] fn` のフラットな並びには
原理的に当てはまらない。

なぜ lexer が要るか (行ベース近似では壊れる)
--------------------------------------------
`common/src/project.rs:1815` に `fs::write(&path, "not valid json {").unwrap();` がある。
文字列の中の対応しない `{` で naive な brace カウンタが desync し、`#[cfg(test)]` の
範囲決定が壊れる。誤差が有界でないので近似は許されない。
`common/src/video_fx.rs` の `wgsl: r#"…"#` に埋め込まれた WGSL が行頭 `//` を含む問題も、
lexer にすれば同時に片付く。構文解析 (AST) は不要 — 字句解析で足りる。
`syn` / `proc-macro2` は使わない (lint が cargo ビルドを前提にしてしまう)。

なぜ bash ではなく Python か
----------------------------
`scripts/arch_lint.sh` 冒頭の「正規表現にバックスラッシュを使わない」節が記録しているとおり、MSYS2 の make から Git の grep を
起動すると **argv のバックスラッシュが落ちる**。2026-08-22 にはそれで 8 検査中 6 つが
無言で無効化され、違反 7 行を抱えたまま「OK (違反なし)」を出していた。Python 実装には
argv の往復が無いので、この故障モード自体が消滅する。**arch_lint.sh 側は本スクリプトの
stdout を読むだけに留め、パターンを shell に持たせないこと。**

このスクリプトは「行分類の SSoT」でもある
-----------------------------------------
`arch_lint.sh` の `strip_comments` (check 1/2/3/5/12 の共有フィルタ) が `--filter-comments`
を呼ぶので、**「コメント内の言及は違反に数えない」の定義もここが決める**。
旧実装は「行頭が `//`」を見るだけの近似で、2 方向に間違えていた:
  - raw string 中の行頭 `//` をコメントと誤判定して落とす = 違反の取りこぼし
  - `/* … */` の中に書かれた違反パターンは落とせない = コメント内の言及を違反に数える
なお **write-time ガード (`.claude/guards.jsonl`) は Python の行正規表現**なので、
raw string / ブロックコメントでは判定が割れる。割れる方向は「ガードのほうが広く nudge」
なので、書く瞬間の注意喚起としては安全側 (`escalate: false` のまま)。

走査が空になったら緑にせず落とす
--------------------------------
`scan_files()` が空を返すと違反は 0 行になり、`LOC-BUDGET-OK 0 files …` は出るので
arch_lint.sh の完走マーカー検査を素通りして **exit 0 の緑**になる。しかも baseline の
全行が「解消 — baseline から削除してよい」として表示されるので、案内どおり削除すると
**検査が永久に消える**。CLAUDE.md が記録している `guards.jsonl` 消失事故
(`if not isfile: return 0` の fail-open で「無い」と「該当しない」が区別できなかった)
と完全に同型なので、git の失敗と走査下限を **exit 2** で落とす。

関数キーに trait 名と cfg 述語を含める理由
------------------------------------------
`path::型名::関数名` だけでは今日すでに **17 件**衝突する。原因は 2 種類しかない:
  - cfg 対 … `#[cfg(windows)]` / `#[cfg(unix)]` で同名 item が 2 つ並ぶ
              (`common/src/shmem.rs` の `mod imp` × 2 が 6 件、`single_instance.rs` が 2 件、
               `daw_audio/src/main.rs:831,848` の `#[cfg(debug_assertions)]` 対 ほか)
  - 同一型への複数 trait impl … `daw_gui/src/midi_import.rs:120,128` の
              `impl From<std::io::Error> for MidiImportError` と `impl From<midly::Error> for …`
**`#2` の連番で潰すのは不可**。連番は出現順に依存するので、無関係な並べ替えで baseline の
天井が入れ替わる = `scripts/arch_lint.sh` の ratchet が「行番号ではなく内容ハッシュ」にした理由と
同じ故障をキー側に作ることになる。trait 名と cfg 述語をキーに含めると衝突は 0 件になる。
それでも残った衝突は `KEY-COLLISION` として表に出し、人に判断させる
(衝突すると 2 関数が 1 つの天井を共有し、片方の違反が黙って消えるので「既知の負債」ではなく
測定のバグ)。

生成物の判定を行数窓にしない理由
--------------------------------
`ara-sys/build.rs:47` に `.raw_line("// @generated by …")` がある。**生成マーカーの文字列が
コードの中の文字列リテラルとして現れる**ので、先頭 N 行という窓で判定すると N を 47 以上に
した瞬間に build.rs が生成物として走査から丸ごと落ちる。だから判定は
**「ファイル先頭の連続するコメント / 空行ブロックの中にマーカーがある」**ことにする。
先頭コメントブロック規則なら、この行はコード中の文字列リテラルなので原理的に当たらない。

baseline と行内マーカーの違い
-----------------------------
  行内 `arch-lint: allow-file-budget` / `allow-fn-budget` / `allow-fn-nesting`
      … **恒久的に正当**。直す予定は無い。
  `scripts/arch_lint_baseline.txt` の 1 行
      … **既知の負債**。直す予定があり、理由と落とし所を書く。天井 (計測値) つきなので
        baseline 済みでも太れない。
区別しないと、負債が「正当」として永久に隠れる。

使い方:
  python scripts/loc_budget.py --check            # 違反を stdout へ (arch_lint.sh が読む)
  python scripts/loc_budget.py --report           # 上位ファイル / 関数の一覧 (人が読む)
  python scripts/loc_budget.py --self-test        # 判定器そのものの自己検査
  python scripts/loc_budget.py --filter-comments  # stdin の path:line:content からコメント行を落とす
"""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
from dataclasses import dataclass, field
from pathlib import Path
from typing import Iterable, Iterator

for _stream in (sys.stdout, sys.stderr):
    try:
        _stream.reconfigure(encoding="utf-8", errors="replace")
    except (AttributeError, ValueError):  # pragma: no cover
        pass

ROOT = Path(__file__).resolve().parent.parent

FILE_NCLOC_BUDGET = 1000
FN_NCLOC_BUDGET = 300
FN_INDENT_BUDGET = 6
INDENT_WIDTH = 4                      # rustfmt の既定。tab はこの幅で展開する
GEN_MARKERS = ("automatically generated by", "@generated", "code generated")
# 生成マーカーを探す範囲は **行数窓ではなく「先頭の連続コメント/空行ブロック」**。
# 行数窓にすると ara-sys/build.rs:47 の .raw_line("// @generated …") に届いた瞬間、
# build.rs が生成物として走査から丸ごと落ちる。定数を持たないこと自体が仕様。
ALLOW_MARKER = "arch-lint: allow-"    # + "file-budget" / "fn-budget" / "fn-nesting"
MIN_SCANNED_FILES = 200               # 今日 389。半分を割ったら走査が壊れたと見なす


class LocBudgetError(Exception):
    """検査器そのものが壊れている状態。**緑にせず exit 2 で落とす**ためだけに使う。"""


# ---------------------------------------------------------------- 字句解析
#
# 1 文字ずつ走査する状態機械。外部ライブラリは使わない (正規表現は前置きの識別だけ)。


@dataclass(frozen=True)
class Token:
    text: str    # 識別子 / 数値 / 記号 / "<lit>" (文字列・char) / "<lifetime>"
    line: int    # 0-based


@dataclass
class Lexed:
    rel: str
    lines: list[str]
    kind: list[str]            # 'code' | 'doc' | 'comment' | 'blank' (テスト判定前)
    indent: list[int | None]   # code 行のうち「行頭が literal/comment の継続でない」行だけ段数
    tokens: list[Token]


# raw string の前置き。`br` `rb` `cr` `rc` `r` + `#`*n + `"`。**識別子より先に試す**。
_RAWSTR_RE = re.compile(r'(?:br|rb|cr|rc|r)(#*)"')
# byte string / C string。`b"` `c"`。
_BYTESTR_RE = re.compile(r'[bc]"')
# 生の識別子 `r#type`。raw string と紛らわしいので明示的に扱う。
_RAWIDENT_RE = re.compile(r"r#(?![\"#])[A-Za-z_][A-Za-z0-9_]*")

# 多文字記号。**`->` を 1 トークンにするのは必須** — 1 文字ずつに割ると
# `fn f() -> bool {` の `>` が angle 深さを 1 減らし、本体の開き `{` を取り違える。
_SYM3 = ("..=",)
_SYM2 = ("->", "=>", "::", "..", "<<", ">>", "<=", ">=", "==", "!=", "&&")


def _split_lines(src: str) -> list[str]:
    """物理行へ割る。**universal newlines を使わない** (単独 CR まで改行に化けて
    `wc -l` と食い違う)。末尾が改行で終わっていたら最後の空要素を 1 つだけ落とす。
    CRLF のファイルが 28 本あるので、各行の末尾 `\\r` を 1 つだけ落とす。"""
    if src == "":
        return []
    parts = src.split("\n")
    if src.endswith("\n"):
        parts.pop()
    return [p[:-1] if p.endswith("\r") else p for p in parts]


def _indent_steps(line: str) -> int:
    """行頭の空白を tab=4 で展開し、4 で割った商 = インデント段数。**絶対値**で測る
    (mod / impl のラッパも段数に数える)。r.md #77 が使っている指標と揃えるため。"""
    col = 0
    for ch in line:
        if ch == " ":
            col += 1
        elif ch == "\t":
            col = (col // INDENT_WIDTH + 1) * INDENT_WIDTH
        else:
            break
    return col // INDENT_WIDTH


def _is_ident(text: str) -> bool:
    """**lex() が識別子として切り出す規則と同一にする。** ASCII 限定の正規表現にすると
    Rust が許す非 ASCII 識別子 (`fn 日本語名()`) で `fn` の次が識別子と見なされず、
    その関数が **黙って計測から落ちる** (= 違反が消える方向の故障)。
    `<lit>` / `<lifetime>` は `<` で始まるのでここには当たらない。"""
    if not text:
        return False
    if not (text[0].isalpha() or text[0] == "_"):
        return False
    return all(ch.isalnum() or ch == "_" for ch in text[1:])


def lex(src: str, rel: str = "<mem>") -> Lexed:
    """Rust の字句解析。行分類 (code / doc / comment / blank) とトークン列を返す。

    行分類は相互排他で、この順に決める:
        code    … コメントに属さない非空白文字が 1 つ以上ある行 (文字列の中身を含む)
        doc     … code でなく、doc comment の非空白文字がある行
        comment … code でも doc でもなく、通常コメントの非空白文字がある行
        blank   … 上のいずれでもない
    """
    lines = _split_lines(src)
    text = "\n".join(lines)
    n = len(text)
    nlines = len(lines)
    f_code = [False] * nlines
    f_doc = [False] * nlines
    f_comment = [False] * nlines
    # carry[i] = 行 i の最初の非空白文字が、前の行から続く文字列リテラル /
    # ブロックコメントの内側にある。これを見ないと common/src/video_fx.rs の WGSL の
    # 字下げが関数のネスト段数に化ける。
    carry = [False] * nlines
    tokens: list[Token] = []
    i = 0
    line = 0

    def consume(start: int, end: int, bucket: list[bool], cont: bool) -> None:
        """[start, end) を bucket に記録して現在行を進める。cont=True なら
        またいだ先の行を「継続行」として記録する (文字列リテラル / ブロックコメント)。"""
        nonlocal line
        seg = text[start:end]
        if "\n" not in seg:
            if seg.strip():
                bucket[line] = True
            return
        parts = seg.split("\n")
        for k, p in enumerate(parts):
            if p.strip() and line + k < nlines:
                bucket[line + k] = True
        if cont:
            for k in range(1, len(parts)):
                if line + k < nlines:
                    carry[line + k] = True
        line += len(parts) - 1

    while i < n:
        ch = text[i]
        if ch in " \t\r":
            i += 1
            continue
        if ch == "\n":
            line += 1
            i += 1
            continue

        # --- 行コメント。3 文字目が `/` または `!` かつ `////` でないなら doc。
        if ch == "/" and i + 1 < n and text[i + 1] == "/":
            j = text.find("\n", i)
            if j < 0:
                j = n
            head3 = text[i:i + 3]
            head4 = text[i:i + 4]
            is_doc = (head3 == "///" and head4 != "////") or head3 == "//!"
            consume(i, j, f_doc if is_doc else f_comment, False)
            i = j
            continue

        # --- ブロックコメント。**ネストを数える** (`/* /* */ */` が 1 個)。
        if ch == "/" and i + 1 < n and text[i + 1] == "*":
            head3 = text[i:i + 3]
            head4 = text[i:i + 4]
            is_doc = (head3 == "/**" and head4 != "/**/") or head3 == "/*!"
            depth = 0
            j = i
            while j < n:
                if text[j:j + 2] == "/*":
                    depth += 1
                    j += 2
                    continue
                if text[j:j + 2] == "*/":
                    depth -= 1
                    j += 2
                    if depth == 0:
                        break
                    continue
                j += 1
            j = min(j, n)
            consume(i, j, f_doc if is_doc else f_comment, True)
            i = j
            continue

        # --- raw string (中の `//` `/*` `{` `}` は一切解釈しない)
        m = _RAWSTR_RE.match(text, i)
        if m:
            closer = '"' + m.group(1)
            j = text.find(closer, m.end())
            j = n if j < 0 else j + len(closer)
            tokens.append(Token("<lit>", line))
            consume(i, j, f_code, True)
            i = j
            continue

        # --- 生の識別子 r#type (raw string と紛らわしいので raw string の後に試す)
        m = _RAWIDENT_RE.match(text, i)
        if m:
            tokens.append(Token(m.group(0)[2:], line))
            consume(i, m.end(), f_code, False)
            i = m.end()
            continue

        # --- 文字列 / byte string / C string
        quote_at = -1
        if ch == '"':
            quote_at = i
        elif _BYTESTR_RE.match(text, i):
            quote_at = i + 1
        if quote_at >= 0:
            j = quote_at + 1
            while j < n:
                c = text[j]
                if c == "\\":
                    j += 2
                    continue
                if c == '"':
                    j += 1
                    break
                j += 1
            tokens.append(Token("<lit>", line))
            consume(i, min(j, n), f_code, True)
            i = min(j, n)
            continue

        # --- char リテラル / ライフタイム。`'ident` は閉じ `'` を持たない。
        #     判別: 直後が `\` (エスケープ) か、2 つ先が `'` なら char。それ以外は
        #     ライフタイム。`'_'` は char、`'_` はライフタイムでどちらも正しく割れる。
        if ch == "'" or (ch == "b" and i + 1 < n and text[i + 1] == "'"):
            start = i
            q = i if ch == "'" else i + 1
            is_char = (q + 1 < n and text[q + 1] == "\\") or (q + 2 < n and text[q + 2] == "'")
            if is_char:
                # `\` は **次の 1 文字ごと飛ばす**。`'\\'` を「エスケープ開始が 2 つ」と
                # 読むと閉じ `'` を食い潰し、そこから先の字句解析が丸ごとずれる
                # (ui/crates/ui/src/shortcut.rs:500 の `('\\', ...)` で実際に起きた)。
                j = q + 1
                while j < n:
                    if text[j] == "\\":
                        j += 2
                        continue
                    if text[j] == "'":
                        j += 1
                        break
                    if text[j] == "\n":
                        break
                    j += 1
                j = min(j, n)
                tokens.append(Token("<lit>", line))
                consume(start, j, f_code, False)
                i = j
                continue
            if ch == "b":
                # b' で始まったのに char として閉じない = 実質ありえない。1 文字進めて逃げる。
                tokens.append(Token("b", line))
                consume(start, start + 1, f_code, False)
                i = start + 1
                continue
            j = i + 1
            while j < n and (text[j].isalnum() or text[j] == "_"):
                j += 1
            tokens.append(Token("<lifetime>", line))
            consume(i, j, f_code, False)
            i = j
            continue

        # --- 識別子 (unicode 識別子も許す)
        if ch.isalpha() or ch == "_":
            j = i + 1
            while j < n and (text[j].isalnum() or text[j] == "_"):
                j += 1
            tokens.append(Token(text[i:j], line))
            consume(i, j, f_code, False)
            i = j
            continue

        # --- 数値。`.` は直後が数字のときだけ取り込む (`1..2` を壊さない)。
        if ch.isdigit():
            j = i + 1
            while j < n:
                c = text[j]
                if c.isalnum() or c == "_":
                    j += 1
                elif c == "." and j + 1 < n and text[j + 1].isdigit():
                    j += 2
                else:
                    break
            tokens.append(Token(text[i:j], line))
            consume(i, j, f_code, False)
            i = j
            continue

        # --- 記号 (多文字を優先)
        sym = ""
        if text[i:i + 3] in _SYM3:
            sym = text[i:i + 3]
        elif text[i:i + 2] in _SYM2:
            sym = text[i:i + 2]
        else:
            sym = ch
        tokens.append(Token(sym, line))
        consume(i, i + len(sym), f_code, False)
        i += len(sym)

    kind: list[str] = []
    for k in range(nlines):
        if f_code[k]:
            kind.append("code")
        elif f_doc[k]:
            kind.append("doc")
        elif f_comment[k]:
            kind.append("comment")
        else:
            kind.append("blank")

    indent: list[int | None] = []
    for k in range(nlines):
        if kind[k] == "code" and not carry[k]:
            indent.append(_indent_steps(lines[k]))
        else:
            indent.append(None)

    return Lexed(rel=rel, lines=lines, kind=kind, indent=indent, tokens=tokens)


# ---------------------------------------------------------------- 属性


def _parse_attr(tokens: list[Token], i: int) -> tuple[str, str, int] | None:
    """tokens[i] が `#` のとき属性を読む。戻り値は (raw 連結, <lit> を空にした連結, 次の位置)。

    `<lit>` を空にした版を持つのは `#[cfg(feature = "test")]` を cfg(test) と
    誤検出しないため。キーに載せる版 (raw) では `<lit>` をそのまま残す。"""
    n = len(tokens)
    j = i + 1
    if j < n and tokens[j].text == "!":
        j += 1
    if j >= n or tokens[j].text != "[":
        return None
    depth = 1
    k = j + 1
    parts: list[str] = []
    while k < n:
        t = tokens[k].text
        if t == "[":
            depth += 1
        elif t == "]":
            depth -= 1
            if depth == 0:
                raw = "".join(parts)
                nolit = "".join("" if p == "<lit>" else p for p in parts)
                return raw, nolit, k + 1
        parts.append(t)
        k += 1
    return None


_CFG_TEST_RE = re.compile(r"(?<![A-Za-z0-9_])test(?![A-Za-z0-9_])")


def _strip_not_groups(text: str) -> str:
    """`not(…)` の部分木を丸ごと落とす。**`cfg(not(test))` を「テスト」と読まないため。**

    `not(test)` は「テストビルド **以外**でだけコンパイルされる」= production コードなので、
    テスト扱いにすると **production が丸ごと budget から消えて緑になる** (このリポジトリが
    最も警戒する false green)。素朴に `test` の語を探すだけだと
    `cfg(not(test))` / `cfg(all(not(test), windows))` が全部テスト扱いになる。
    `not(…)` を先に落としてから語を探せば、`cfg(all(test, not(windows)))` は
    テストのまま拾える。"""
    out: list[str] = []
    i = 0
    n = len(text)
    while i < n:
        if text.startswith("not(", i):
            depth = 0
            k = i + 3            # `(` の位置
            while k < n:
                if text[k] == "(":
                    depth += 1
                elif text[k] == ")":
                    depth -= 1
                    if depth == 0:
                        break
                k += 1
            i = k + 1
            continue
        out.append(text[i])
        i += 1
    return "".join(out)


def _is_cfg_test(nolit: str) -> bool:
    """`cfg(all(test, windows))` / `cfg(any(test, …))` は意図的に拾う。
    **`cfg(not(test))` 系は拾わない** (production 専用コードなので。`_strip_not_groups`)。"""
    if not nolit.startswith("cfg("):
        return False
    return bool(_CFG_TEST_RE.search(_strip_not_groups(nolit)))


def _cfg_suffix(pending: list[tuple[str, int]]) -> str:
    """item に付いた `#[cfg(…)]` を正規化してキーの接尾辞にする。
    cfg 以外の属性 (`#[allow(...)]` / `#[derive(...)]` / doc 属性) はキーに入れない。"""
    cfgs = [c for c, _ in pending if c.startswith("cfg(")]
    return "[" + ",".join(cfgs) + "]" if cfgs else ""


# ---------------------------------------------------------------- cfg(test) 範囲


def _item_end_line(tokens: list[Token], j: int) -> int:
    """item の終端行。深さ 0 から始め、`(` `[` `{` で +1、`)` `]` `}` で −1。

    **−1 した結果が 0 になった `}` がその item の終端**。減算「前」の深さを見る実装に
    すると `mod tests { … }` は深さ 1 のまま `}` を見送ってファイル末尾まで走り、
    production コードが丸ごとテスト扱いになって budget が空振りする。

    **item ではないもの (struct の field / enum の variant / match の arm) に
    `#[cfg(test)]` が付いた場合の暴走を必ず止める**。それらは `;` でも `}` でも終わらないので、
    上の 2 規則だけだとファイル末尾まで走り、**残り全部がテスト扱い = 違反が黙って消える**。
    止め方は 2 つ:
      - 深さ 0 の `,` (囲みの `<…>` の中は数えない。`fn f<A, B>()` を切らないため)
      - 深さが負になる `)` `]` `}` = 囲みブロックの終わり。そこで打ち切る"""
    n = len(tokens)
    depth = 0
    angle = 0
    k = j
    while k < n:
        t = tokens[k].text
        if t in ("(", "[", "{"):
            depth += 1
        elif t in (")", "]", "}"):
            depth -= 1
            if depth == 0 and t == "}":
                if k + 1 < n and tokens[k + 1].text == ";":
                    return tokens[k + 1].line
                return tokens[k].line
            if depth < 0:
                # 囲みブロックの終わり。item ではないものに付いていた = ここで打ち切る。
                return tokens[k].line
        elif t == ";" and depth == 0:
            return tokens[k].line
        elif t == "," and depth == 0 and angle == 0:
            return tokens[k].line
        elif t == "<" and depth == 0:
            prev = tokens[k - 1].text if k > 0 else ""
            if _is_ident(prev) or prev in ("::", ">"):
                angle += 1
        elif t == ">" and depth == 0:
            angle = max(0, angle - 1)
        elif t == ">>" and depth == 0:
            angle = max(0, angle - 2)
        k += 1
    return tokens[n - 1].line if n else 0


def _mod_decl(tokens: list[Token], j: int) -> tuple[str, int] | None:
    """item が `[pub[(…)]] mod NAME ;` の形なら (NAME, 宣言行) を返す。"""
    n = len(tokens)
    k = j
    if k < n and tokens[k].text == "pub":
        k += 1
        if k < n and tokens[k].text == "(":
            depth = 1
            k += 1
            while k < n and depth > 0:
                if tokens[k].text == "(":
                    depth += 1
                elif tokens[k].text == ")":
                    depth -= 1
                k += 1
    if k + 2 >= n or tokens[k].text != "mod":
        return None
    if not _is_ident(tokens[k + 1].text):
        return None
    if tokens[k + 2].text != ";":
        return None
    return tokens[k + 1].text, tokens[k].line


def cfg_test_items(lx: Lexed) -> tuple[list[tuple[int, int]], list[tuple[str, int]]]:
    """`#[cfg(test)]` が付いた **あらゆる item** の範囲と、`#[cfg(test)] mod X;` の宣言を返す。

    範囲は「その item の最初の属性行の `#` がある行」から「item の終端行」まで。
    属性より上にある doc comment は範囲外 = doc として数える。だから **属性は 1 個ずつでは
    なく「連続した属性の塊」として読む** — `#[allow(x)]` が `#[cfg(test)]` の上にあるとき、
    範囲は `#[allow(x)]` の行から始まる。

    内部属性 (`#![…]`) は囲んでいる module に掛かるもので「次の item」には掛からないので、
    塊に含めない (拾うと後続の item の範囲が前へ伸びる)。"""
    tokens = lx.tokens
    n = len(tokens)
    ranges: list[tuple[int, int]] = []
    mod_decls: list[tuple[str, int]] = []
    i = 0
    while i < n:
        if tokens[i].text != "#":
            i += 1
            continue
        if i + 1 < n and tokens[i + 1].text == "!":
            # 内部属性。塊の開始にしない (読み飛ばすだけ)。
            parsed = _parse_attr(tokens, i)
            i = parsed[2] if parsed is not None else i + 1
            continue
        parsed = _parse_attr(tokens, i)
        if parsed is None:
            i += 1
            continue
        run_start_line = tokens[i].line
        is_test = _is_cfg_test(parsed[1])
        j = parsed[2]
        while j < n and tokens[j].text == "#":
            if j + 1 < n and tokens[j + 1].text == "!":
                break
            p2 = _parse_attr(tokens, j)
            if p2 is None:
                break
            is_test = is_test or _is_cfg_test(p2[1])
            j = p2[2]
        if is_test:
            ranges.append((run_start_line, _item_end_line(tokens, j)))
            md = _mod_decl(tokens, j)
            if md is not None:
                mod_decls.append(md)
        # 入れ子の `#[cfg(test)]` も拾えるよう、走査は item 本体の先頭から続ける
        i = j
    return ranges, mod_decls


# ---------------------------------------------------------------- 関数 item


def _brace_pairs(tokens: list[Token]) -> dict[int, int]:
    """`{` のトークン位置 → 対応する `}` のトークン位置。1 パスで作る
    (関数ごとに前方走査すると O(n^2) になる)。"""
    pairs: dict[int, int] = {}
    stack: list[int] = []
    for k, t in enumerate(tokens):
        if t.text == "{":
            stack.append(k)
        elif t.text == "}":
            if stack:
                pairs[stack.pop()] = k
    return pairs


def _find_body_open(tokens: list[Token], start: int) -> tuple[int, bool]:
    """paren / bracket / angle の 3 深さがすべて 0 のときに現れた最初の `{` を返す。

    `;` に当たったら本体無し (trait / extern の宣言)。bracket を数えるので
    `fn f<const N: usize>() -> [u8; { N * 2 }]` の `{` を本体と誤認しない。
    angle を数えるので `Foo<{ N }>` も巻き込まない。"""
    n = len(tokens)
    paren = bracket = angle = 0
    j = start
    while j < n:
        t = tokens[j].text
        if t == "{":
            if paren == 0 and bracket == 0 and angle == 0:
                return j, True
        elif t == ";":
            if paren == 0 and bracket == 0 and angle == 0:
                return j, False
        if t == "(":
            paren += 1
        elif t == ")":
            paren = max(0, paren - 1)
        elif t == "[":
            bracket += 1
        elif t == "]":
            bracket = max(0, bracket - 1)
        elif t == "<":
            prev = tokens[j - 1].text if j > 0 else ""
            if _is_ident(prev) or prev in ("::", ">"):
                angle += 1
        elif t == ">":
            angle = max(0, angle - 1)
        elif t == ">>":
            angle = max(0, angle - 2)
        j += 1
    return -1, False


def _skip_generics(tokens: list[Token], j: int) -> int:
    """tokens[j] が `<` ならその対応する `>` の次の位置を返す。そうでなければ j。"""
    n = len(tokens)
    if j >= n or tokens[j].text != "<":
        return j
    depth = 1
    j += 1
    while j < n and depth > 0:
        t = tokens[j].text
        if t == "<":
            depth += 1
        elif t == ">":
            depth -= 1
        elif t == ">>":
            depth -= 2
        j += 1
    return j


_SKIP_TYPE_WORDS = {"dyn", "mut", "impl"}


def _first_ident(tokens: list[Token], start: int, stop: int) -> str:
    for j in range(start, min(stop, len(tokens))):
        t = tokens[j].text
        if _is_ident(t) and t not in _SKIP_TYPE_WORDS:
            return t
    return "?"


# 属性と item キーワードの間に挟まってよいトークン。ここに無いものが現れたら
# pending 属性を捨てる (無関係な item の cfg が後続の fn のキーへ漏れるのを防ぐ)。
_TRANSPARENT = {"(", ")", "::", "<lit>"}

# `impl` の直前がこれらなら **型位置の `impl Trait`** (引数 / 戻り値 / 型引数) であって
# item の `impl` ブロックではない。区別しないと `fn f(x: impl Foo) { … }` の
# `impl` が「その関数自身の本体 `{`」を impl の本体と誤認し、関数の中に `Foo` という
# 偽のスコープが立って、入れ子の fn のキーが `<rel>::Foo::inner` に化ける。
_IMPL_TYPE_POS = {":", "->", "<", "(", "[", ",", "&", "+", "=", "|", "dyn", "as"}


def fn_items(lx: Lexed) -> list[tuple[str, int, int, int, int]]:
    """(qualified_key, attr_line, decl_line, body_open_line, body_close_line) を返す。
    すべて 0-based。key は `<rel>::<Scope>::<name>` (スコープが空なら `<rel>::<name>`)。

    **attr_line を返すのは必須** — 行内マーカーは「最初の属性行から本体の開き行まで」を
    探すので、宣言行から後方走査すると doc comment をどこまで遡るかが曖昧になり、
    上にある無関係な関数のマーカーを拾い得る。"""
    tokens = lx.tokens
    n = len(tokens)
    pairs = _brace_pairs(tokens)
    scope_open: dict[int, str] = {}      # 本体の開き `{` のトークン位置 → スコープ名
    scopes: list[tuple[str, int]] = []   # (名前, push 時点の brace 深さ)
    pending: list[tuple[str, int]] = []  # (属性の raw 連結, `#` の行)
    out: list[tuple[str, int, int, int, int]] = []
    depth = 0
    i = 0
    while i < n:
        t = tokens[i].text

        if t == "#":
            parsed = _parse_attr(tokens, i)
            if parsed is not None:
                # 内部属性 (`#![…]`) は囲む module に掛かるので、次の item には積まない
                # (積むと attr_line と cfg 接尾辞が無関係な fn へ漏れる)。
                if not (i + 1 < n and tokens[i + 1].text == "!"):
                    pending.append((parsed[0], tokens[i].line))
                i = parsed[2]
                continue

        if t == "{":
            if i in scope_open:
                scopes.append((scope_open[i], depth))
            depth += 1
            pending = []
            i += 1
            continue

        if t == "}":
            depth -= 1
            while scopes and scopes[-1][1] >= depth:
                scopes.pop()
            pending = []
            i += 1
            continue

        if t == "mod" and i + 1 < n and _is_ident(tokens[i + 1].text):
            if i + 2 < n and tokens[i + 2].text == "{":
                scope_open[i + 2] = tokens[i + 1].text + _cfg_suffix(pending)
            pending = []
            i += 1
            continue

        if t == "trait" and i + 1 < n and _is_ident(tokens[i + 1].text):
            body, has = _find_body_open(tokens, i + 2)
            if has:
                scope_open[body] = tokens[i + 1].text + _cfg_suffix(pending)
            pending = []
            i += 1
            continue

        if t == "impl":
            prev = tokens[i - 1].text if i > 0 else ""
            if prev in _IMPL_TYPE_POS:
                # 型位置の `impl Trait`。item ではないので scope を作らない。
                i += 1
                continue
            type_start = _skip_generics(tokens, i + 1)
            body, has = _find_body_open(tokens, type_start)
            if has:
                # paren / bracket / angle がすべて 0 の位置に `for` があれば trait impl。
                paren = bracket = angle = 0
                for_pos = -1
                for j in range(type_start, body):
                    tt = tokens[j].text
                    if tt == "for" and paren == 0 and bracket == 0 and angle == 0:
                        for_pos = j
                        break
                    if tt == "(":
                        paren += 1
                    elif tt == ")":
                        paren = max(0, paren - 1)
                    elif tt == "[":
                        bracket += 1
                    elif tt == "]":
                        bracket = max(0, bracket - 1)
                    elif tt == "<":
                        prev = tokens[j - 1].text if j > 0 else ""
                        if _is_ident(prev) or prev in ("::", ">"):
                            angle += 1
                    elif tt == ">":
                        angle = max(0, angle - 1)
                    elif tt == ">>":
                        angle = max(0, angle - 2)
                if for_pos >= 0:
                    trait_name = "".join(tk.text for tk in tokens[type_start:for_pos])
                    type_name = _first_ident(tokens, for_pos + 1, body)
                    scope_open[body] = f"{type_name}[{trait_name}]" + _cfg_suffix(pending)
                else:
                    type_name = _first_ident(tokens, type_start, body)
                    scope_open[body] = type_name + _cfg_suffix(pending)
            pending = []
            i += 1
            continue

        # 関数 item の判定: トークン `fn` の次が識別子 (関数ポインタ型 `fn(u32) -> u32` を除外)
        if t == "fn" and i + 1 < n and _is_ident(tokens[i + 1].text):
            name = tokens[i + 1].text + _cfg_suffix(pending)
            attr_line = pending[0][1] if pending else tokens[i].line
            decl_line = tokens[i].line
            body, has = _find_body_open(tokens, i + 2)
            if has:
                close = pairs.get(body, -1)
                if close >= 0:
                    scope = "::".join(s for s, _ in scopes)
                    key = f"{lx.rel}::{scope}::{name}" if scope else f"{lx.rel}::{name}"
                    out.append((key, attr_line, decl_line,
                                tokens[body].line, tokens[close].line))
            pending = []
            i += 1
            continue

        if not (_is_ident(t) or t in _TRANSPARENT):
            pending = []
        i += 1
    return out


# ---------------------------------------------------------------- 走査対象


def scan_files(argv: list[str] | None = None) -> list[str]:
    """走査対象を **原理で決める**: git が知っている `.rs` すべて。

    `--others --exclude-standard` を必ず付ける。`git ls-files` だけだと `git add` 前の
    新規巨大ファイルを見逃す = 検査器が黙って空振りする経路を新設してしまう。
    (`--exclude-standard` があるので `target/` や `third_party/` は .gitignore で落ちる。)

    **git が失敗したら空リストへ縮退させず例外**にする。空リストは「違反 0 + 完走マーカー
    あり」= 緑になり、しかも baseline 全行が「解消」として削除を案内される。"""
    cmd = argv or ["git", "ls-files", "-z", "--cached", "--others",
                   "--exclude-standard", "--", "*.rs"]
    try:
        proc = subprocess.run(cmd, cwd=ROOT, capture_output=True)
    except OSError as exc:
        raise LocBudgetError(f"git を起動できません ({cmd[0]}): {exc}") from exc
    if proc.returncode != 0:
        detail = proc.stderr.decode("utf-8", "replace").strip().splitlines()
        raise LocBudgetError(
            f"`{' '.join(cmd)}` が exit {proc.returncode} で失敗しました: "
            f"{detail[-1] if detail else '(詳細なし)'}"
        )
    out = proc.stdout.decode("utf-8", "replace")
    return [p for p in out.split("\0") if p]


def is_generated(lx: Lexed) -> bool:
    """ファイル先頭の連続するコメント / 空行ブロックの中に生成マーカーがあるか。
    **最初に `code` 行が現れた時点で打ち切る** — 行数窓にすると
    ara-sys/build.rs:47 の `.raw_line("// @generated …")` に届いて build.rs が落ちる。"""
    for k, kind in enumerate(lx.kind):
        if kind == "code":
            return False
        if kind in ("comment", "doc"):
            low = lx.lines[k].lower()
            if any(mark in low for mark in GEN_MARKERS):
                return True
    return False


def is_integration_test(rel: str) -> bool:
    """`tests/` `benches/` 直下の統合テスト。Rust の統合テストは crate 全体がテスト
    ビルド専用なので `#[cfg(test)]` を書かない = 属性経路にも mod 経路にも当たらない。
    判定は「パス成分に tests / benches があり、その親ディレクトリに Cargo.toml がある」
    = Cargo の規約そのもの。"""
    parts = rel.split("/")
    for k, p in enumerate(parts[:-1]):
        if p not in ("tests", "benches"):
            continue
        parent = "/".join(parts[:k])
        manifest = (ROOT / parent / "Cargo.toml") if parent else (ROOT / "Cargo.toml")
        if manifest.is_file():
            return True
    return False


def submodule_candidates(rel: str, name: str) -> list[str]:
    """`mod NAME;` の解決先候補。repo に `#[path = "…"] mod` は 1 件も無いので
    Rust の既定規則だけで足りる。将来 `#[path]` が入ったら解決に失敗するので、
    黙って外さず `UNRESOLVED-MOD` として表に出す。"""
    p = Path(rel)
    parent = p.parent.as_posix()
    parent = "" if parent == "." else parent + "/"
    if p.stem in ("mod", "lib", "main"):
        base = parent
    else:
        base = f"{parent}{p.stem}/"
    return [f"{base}{name}.rs", f"{base}{name}/mod.rs"]


# ---------------------------------------------------------------- 計測


@dataclass
class FileMetrics:
    rel: str
    raw: int          # 物理行
    ncloc: int        # 実コード行
    doc: int
    comment: int
    blank: int
    test: int         # テスト範囲に入る行 (種別を問わず)


@dataclass
class FnMetrics:
    key: str          # "<rel>::<Scope>::<name>" (スコープが空なら "<rel>::<name>")
    rel: str
    line: int         # 1-based。fn の宣言行
    attr_line: int    # 1-based。その fn の最初の属性行。無ければ line と同値
    body_open: int    # 1-based。本体の開き `{` の行。行内マーカーの探索範囲の下端
    ncloc: int
    max_indent: int
    deep_lines: int   # indent >= FN_INDENT_BUDGET の行数。ratchet の第 2 成分


@dataclass
class FileScan:
    metrics: FileMetrics
    fns: list[FnMetrics]
    lines: list[str]
    generated: bool
    force_test: bool
    test_mods: list[str] = field(default_factory=list)      # 解決できた `mod X;` の rel
    unresolved: list[tuple[int, str]] = field(default_factory=list)  # (1-based 行, 行内容)

    @property
    def rel(self) -> str:
        return self.metrics.rel


def _has_allow(lines: list[str], lo: int, hi: int, marker: str) -> bool:
    for k in range(max(0, lo), min(hi + 1, len(lines))):
        if marker in lines[k]:
            return True
    return False


def measure_source(rel: str, src: str, force_test: bool = False) -> FileScan:
    """**--check と --self-test が同じ経路を通るための分岐点**。合成フィクスチャも
    リポジトリのファイルも、必ずこの関数を通す。別実装で self-test を書くと
    「canary が検査対象と別物を試す」(scripts/arch_lint.sh の「検査パターンは 1 箇所で定義」が実例つきで戒めている
    失敗) を再生産する。"""
    lx = lex(src, rel)
    raw = len(lx.lines)
    generated = is_generated(lx)

    ranges, mod_decls = cfg_test_items(lx)
    test_mods: list[str] = []
    unresolved: list[tuple[int, str]] = []
    for name, line0 in mod_decls:
        hit = ""
        for cand in submodule_candidates(rel, name):
            if (ROOT / cand).is_file():
                hit = cand
                break
        if hit:
            test_mods.append(hit)
        else:
            content = lx.lines[line0].strip() if line0 < raw else f"mod {name};"
            unresolved.append((line0 + 1, content))

    if force_test:
        test_set: set[int] = set(range(raw))
    else:
        test_set = set()
        for a, b in ranges:
            test_set.update(range(a, min(b, raw - 1) + 1))

    ncloc = doc = comment = blank = 0
    for k in range(raw):
        if k in test_set:
            continue
        kind = lx.kind[k]
        if kind == "code":
            ncloc += 1
        elif kind == "doc":
            doc += 1
        elif kind == "comment":
            comment += 1
        else:
            blank += 1

    metrics = FileMetrics(rel=rel, raw=raw, ncloc=ncloc, doc=doc,
                          comment=comment, blank=blank, test=len(test_set))
    total = ncloc + doc + comment + blank + metrics.test
    if total != raw:
        raise LocBudgetError(
            f"保存則違反 {rel}: ncloc {ncloc} + doc {doc} + comment {comment} + "
            f"blank {blank} + test {metrics.test} = {total} != raw {raw}"
        )

    fns: list[FnMetrics] = []
    if not force_test:
        for key, attr_line, decl_line, body_open, body_close in fn_items(lx):
            if decl_line in test_set:
                continue
            fn_ncloc = 0
            max_indent = 0
            deep = 0
            for k in range(body_open, min(body_close, raw - 1) + 1):
                if k in test_set:
                    continue
                if lx.kind[k] == "code":
                    fn_ncloc += 1
                ind = lx.indent[k]
                if ind is None:
                    continue
                if ind > max_indent:
                    max_indent = ind
                if ind >= FN_INDENT_BUDGET:
                    deep += 1
            fns.append(FnMetrics(key=key, rel=rel, line=decl_line + 1,
                                 attr_line=attr_line + 1, body_open=body_open + 1,
                                 ncloc=fn_ncloc, max_indent=max_indent, deep_lines=deep))

    return FileScan(metrics=metrics, fns=fns, lines=lx.lines, generated=generated,
                    force_test=force_test, test_mods=test_mods, unresolved=unresolved)


def _read_source(rel: str) -> str:
    """改行変換をせずに読む。`read_text()` / 既定の text mode は universal newlines なので、
    単独 CR (旧 Mac 改行) まで改行に化けて `wc -l` と食い違う。"""
    with open(ROOT / rel, encoding="utf-8", newline="", errors="replace") as fh:
        return fh.read()


def measure(files: list[str]) -> tuple[list[FileScan], int]:
    """生成物を除いて全ファイルを計測する。戻り値は (走査した FileScan, 除外した生成物の数)。"""
    for rel in files:
        if " " in rel:
            raise LocBudgetError(f"パスに空白が含まれています: {rel!r}。"
                                 "arch_lint.sh がパラメータ展開で分解できません。")
    scans: list[FileScan] = []
    generated = 0
    sources: dict[str, str] = {}
    for rel in files:
        try:
            src = _read_source(rel)
        except OSError as exc:
            raise LocBudgetError(f"{rel} を読めません: {exc}") from exc
        sources[rel] = src
        scan = measure_source(rel, src, force_test=is_integration_test(rel))
        if scan.generated:
            generated += 1
            continue
        scans.append(scan)

    if len(scans) < MIN_SCANNED_FILES:
        raise LocBudgetError(
            f"走査できた .rs が {len(scans)} 件しかありません (下限 {MIN_SCANNED_FILES})。"
            "走査そのものが壊れている可能性が高いので、緑にはしません。"
        )

    # `#[cfg(test)] mod X;` が指すファイルは丸ごとテスト扱い (1 段で足りる)。
    forced = {rel for s in scans for rel in s.test_mods}
    if forced:
        by_rel = {s.rel: idx for idx, s in enumerate(scans)}
        for rel in forced:
            idx = by_rel.get(rel)
            if idx is None:
                continue
            scans[idx] = measure_source(rel, sources[rel], force_test=True)

    return scans, generated


def load_repo(files: list[str] | None = None) -> tuple[list[FileScan], int]:
    return measure(scan_files() if files is None else files)


# ---------------------------------------------------------------- 出力


def emit_check(scans: list[FileScan], generated: int = 0) -> list[str]:
    """違反 1 件 1 行。**print せずに行を返す** — `--self-test` が同じ関数を呼んで
    出力そのものを assert できるようにするため。

    budget 形式 (FILE-BUDGET / FN-BUDGET / FN-NESTING):
        CHECK <キー> <計測値(/区切りの整数ベクトル)> <人間向け…>
    grep 形式 (UNRESOLVED-MOD / KEY-COLLISION):
        CHECK <path>:<line>:<content>
    """
    out: list[str] = []

    files = [s for s in scans
             if s.metrics.ncloc > FILE_NCLOC_BUDGET
             and not _has_allow(s.lines, 0, len(s.lines), ALLOW_MARKER + "file-budget")]
    for s in sorted(files, key=lambda s: (-s.metrics.ncloc, s.rel)):
        m = s.metrics
        out.append(f"FILE-BUDGET {m.rel} {m.ncloc} ncloc>{FILE_NCLOC_BUDGET} "
                   f"(raw {m.raw} / doc {m.doc} / comment {m.comment} / test {m.test})")

    # 行内マーカーの探索範囲は **その関数の attr_line から body_open まで**。
    # 宣言行から後方走査して属性を探す実装にしないこと — doc comment をどこまで遡るかが
    # 曖昧になり、上にある無関係な関数のマーカーを拾い得る。範囲は fn_items() が決めた
    # 1 か所だけが権威。
    over_len: list[FnMetrics] = []
    over_nest: list[FnMetrics] = []
    for s in scans:
        for fn in s.fns:
            lo, hi = fn.attr_line - 1, fn.body_open - 1
            if fn.ncloc > FN_NCLOC_BUDGET and not _has_allow(
                    s.lines, lo, hi, ALLOW_MARKER + "fn-budget"):
                over_len.append(fn)
            if fn.max_indent > FN_INDENT_BUDGET and not _has_allow(
                    s.lines, lo, hi, ALLOW_MARKER + "fn-nesting"):
                over_nest.append(fn)
    for fn in sorted(over_len, key=lambda f: (-f.ncloc, f.key)):
        out.append(f"FN-BUDGET {fn.key} {fn.ncloc} ncloc>{FN_NCLOC_BUDGET} "
                   f"@{fn.rel}:{fn.line}")
    for fn in sorted(over_nest, key=lambda f: (-f.max_indent, -f.deep_lines, f.key)):
        out.append(f"FN-NESTING {fn.key} {fn.max_indent}/{fn.deep_lines} "
                   f"indent>{FN_INDENT_BUDGET} @{fn.rel}:{fn.line}")

    n_unresolved = 0
    for s in sorted(scans, key=lambda s: s.rel):
        for line, content in s.unresolved:
            out.append(f"UNRESOLVED-MOD {s.rel}:{line}:{content}")
            n_unresolved += 1

    seen: dict[str, FnMetrics] = {}
    collisions: list[str] = []
    for s in scans:
        for fn in s.fns:
            if " " in fn.key:
                raise LocBudgetError(f"関数キーに空白が含まれています: {fn.key!r}")
            if fn.key in seen:
                collisions.append(f"KEY-COLLISION {fn.rel}:{fn.line}:key collision: {fn.key}")
            else:
                seen[fn.key] = fn
    out.extend(sorted(collisions))

    n_test = sum(1 for s in scans if s.force_test)
    out.append(f"LOC-BUDGET-OK {len(scans)} files / {n_test} test / {generated} generated "
               f"/ {len(collisions)} key-collision / {n_unresolved} unresolved-mod")
    return out


def report(scans: list[FileScan], generated: int) -> int:
    n_test = sum(1 for s in scans if s.force_test)
    all_fns = [fn for s in scans for fn in s.fns]
    keys: dict[str, int] = {}
    for fn in all_fns:
        keys[fn.key] = keys.get(fn.key, 0) + 1
    n_collision = sum(v - 1 for v in keys.values() if v > 1)
    n_unresolved = sum(len(s.unresolved) for s in scans)

    print(f"loc-budget: {len(scans)} ファイル (テスト扱い {n_test} / 生成物 {generated} 除外 "
          f"/ キー衝突 {n_collision} / 未解決 mod {n_unresolved})")
    print(f"  budget: ファイル {FILE_NCLOC_BUDGET:,} 実コード行 / "
          f"関数 {FN_NCLOC_BUDGET:,} 実コード行 / インデント {FN_INDENT_BUDGET} 段")

    print("\n--- ファイル 実コード行 上位 20 ---")
    print(" ncloc    raw    doc   comment  blank   test  path")
    for s in sorted(scans, key=lambda s: -s.metrics.ncloc)[:20]:
        m = s.metrics
        print(f"{m.ncloc:6d} {m.raw:6d} {m.doc:6d} {m.comment:9d} {m.blank:6d} "
              f"{m.test:6d}  {m.rel}")

    print("\n--- 関数 実コード行 上位 20 ---")
    print(" ncloc  indent  path:line  key")
    for fn in sorted(all_fns, key=lambda f: -f.ncloc)[:20]:
        print(f"{fn.ncloc:6d} {fn.max_indent:7d}  {fn.rel}:{fn.line}  {fn.key}")

    print("\n--- 関数 最大インデント 上位 20 ---")
    print(" indent  >=6行  ncloc  path:line  key")
    for fn in sorted(all_fns, key=lambda f: (-f.max_indent, -f.deep_lines))[:20]:
        print(f"{fn.max_indent:7d} {fn.deep_lines:6d} {fn.ncloc:6d}  "
              f"{fn.rel}:{fn.line}  {fn.key}")
    return 0


# ---------------------------------------------------------------- --filter-comments


def filter_comments(rows: Iterable[str], read=_read_source) -> Iterator[str]:
    """`path:line:content` の行を読み、その行が doc / comment に分類されるなら落とす。

    **読めない path / 範囲外の line は落とさずに残す** — 迷ったら違反を表に出す側に倒す。
    黙って捨てると false negative になる。`path:line:content` の形をしていない行は
    そのまま素通しする (呼び出し側の出力を壊さない)。

    `read` を差し替えられるようにしてあるのは **self-test がこの関数そのものを通せる
    ようにするため**。lex() の行分類だけを別に assert すると、フィルタの落とす / 残すの
    向きが反転しても canary が緑のままになる (= check 1/2/3/5/12 の違反が全部消えても
    誰も気付けない)。"""
    cache: dict[str, Lexed | None] = {}
    for row in rows:
        row = row.rstrip("\n").rstrip("\r")
        parts = row.split(":", 2)
        if len(parts) < 3 or not parts[1].isdigit():
            yield row
            continue
        path, lineno_s, _content = parts
        if path not in cache:
            try:
                cache[path] = lex(read(path), path)
            except OSError:
                cache[path] = None
                print(f"loc-budget: [警告] {path} を読めないので落とさず残します", file=sys.stderr)
        lx = cache[path]
        if lx is None:
            yield row
            continue
        idx = int(lineno_s) - 1
        if idx < 0 or idx >= len(lx.kind):
            print(f"loc-budget: [警告] {path}:{lineno_s} は範囲外なので落とさず残します",
                  file=sys.stderr)
            yield row
            continue
        if lx.kind[idx] in ("doc", "comment"):
            continue
        yield row


# ---------------------------------------------------------------- --self-test


def _fixture(rel: str, src: str, force_test: bool = False) -> FileScan:
    return measure_source(rel, src, force_test=force_test)


def _lines_of(scan: FileScan, prefix: str) -> list[str]:
    return [ln for ln in emit_check([scan]) if ln.startswith(prefix + " ")]


def self_test() -> int:
    """合成フィクスチャだけで判定器を検証する (リポジトリの内容に依存させない —
    依存させると「repo が変わった」のか「判定器が壊れた」のか区別できなくなる)。

    フィクスチャは必ず `measure_source()` → `emit_check()` を通す。別実装で assert すると
    canary が検査対象と別物を試すことになる。"""
    fails: list[str] = []
    n_fixture = 0
    n_conserve = 0

    def check(cond: bool, msg: str) -> None:
        nonlocal n_fixture
        n_fixture += 1
        if not cond:
            fails.append(msg)

    def scan(rel: str, src: str, force_test: bool = False) -> FileScan:
        nonlocal n_conserve
        s = _fixture(rel, src, force_test)   # 保存則は measure_source 内で assert 済み
        n_conserve += 1
        return s

    # ---- (A) 分類器 ----------------------------------------------------------
    # 1. raw string 中の行頭 `//` はコメントではない。`{` も解釈しない。
    s = scan("selftest/a1.rs", 'fn f() {\nlet s = r#"\n// これはコメントではない {\n"#;\n}\n')
    check(s.metrics.comment == 0, "A1: raw string 中の // が comment に数えられた")
    check(s.metrics.ncloc == 5, f"A1: ncloc が 5 でない ({s.metrics.ncloc})")

    # 2. 文字列中の対応しない `{` で cfg(test) 範囲が desync しない (project.rs:1815 型)
    src2 = ('#[cfg(test)]\nmod t {\n    fn a() { let s = "not valid json {"; }\n}\n'
            'pub fn production() {\n    let x = 1;\n}\n')
    s = scan("selftest/a2.rs", src2)
    check(s.metrics.test == 4, f"A2: test 範囲が 4 行でない ({s.metrics.test})")
    check(s.metrics.ncloc == 3, f"A2: production が 3 行でない ({s.metrics.ncloc})")

    # 3. ネストしたブロックコメント
    s = scan("selftest/a3.rs", "/* /* ネスト */ まだコメント */\nlet x = 1;\n")
    check(s.metrics.comment == 1 and s.metrics.ncloc == 1, "A3: ネストコメントの分類")

    # 4. mod でなくても cfg(test) なら test 扱い (compile.rs:900 型)
    s = scan("selftest/a4.rs", "#[cfg(test)]\npub(crate) fn f() {\n    let a = 1;\n}\nfn g() {}\n")
    check(s.metrics.test == 4, f"A4: cfg(test) fn が test 扱いでない ({s.metrics.test})")

    # 5. `#[cfg(test)] mod tests;` の宣言を拾う
    lx = lex("#[cfg(test)]\nmod tests;\n", "selftest/a5.rs")
    _r, mods = cfg_test_items(lx)
    check(mods == [("tests", 1)], f"A5: mod 宣言を拾えていない ({mods})")

    # 6. ライフタイムと char を取り違えない。`'}'` で深さが動かない。
    s = scan("selftest/a6.rs", "fn f<'a>(x: &'a str) -> char { '}' }\nfn g() {}\n")
    fns6 = {f.key for f in s.fns}
    check(fns6 == {"selftest/a6.rs::f", "selftest/a6.rs::g"}, f"A6: 関数が拾えていない ({fns6})")

    # 6b. `'\\'` (エスケープされたバックスラッシュ) が閉じ `'` を食い潰さない。
    #     食い潰すと次の `'` まで literal が伸び、そこから先の字句解析が丸ごとずれる
    #     (実装中に ui/crates/ui/src/shortcut.rs:500 で発火した。関数 1 本が消えていた)。
    #     **後続行の分類まで assert する** — 関数が 2 本見つかるだけの assert では、
    #     literal の伸び方によっては偶然通ってしまう。
    s = scan("selftest/a6b.rs",
             "fn f() {\n    let t = [(\"\\\\\", '\\\\'), (\"'\", '\\'')];\n}\n"
             "// ここはコメント\nfn g() {}\n")
    check({f.key for f in s.fns} == {"selftest/a6b.rs::f", "selftest/a6b.rs::g"},
          f"A6b: '\\\\' の後で字句解析がずれた ({[f.key for f in s.fns]})")
    check(s.metrics.comment == 1 and s.metrics.ncloc == 4,
          f"A6b: 後続行の分類が壊れた (comment {s.metrics.comment} / ncloc {s.metrics.ncloc})")

    # 7. `#[cfg(feature = "test")]` を test 扱いにしない
    s = scan("selftest/a7.rs", '#[cfg(feature = "test")]\nfn f() {}\n')
    check(s.metrics.test == 0, f"A7: feature=\"test\" を test 扱いにした ({s.metrics.test})")

    # 8. 関数ポインタ型 / 本体無しの trait 宣言は関数 item ではない
    s = scan("selftest/a8.rs", "type F = fn(u32) -> u32;\ntrait T { fn g(); }\n")
    check(s.fns == [], f"A8: 関数でないものを拾った ({[f.key for f in s.fns]})")

    # 9. `////` は comment、`///` `//!` `/** */` は doc
    s = scan("selftest/a9.rs", "//// 4 本\n/// doc\n//! inner\n/** doc */\n")
    check(s.metrics.comment == 1 and s.metrics.doc == 3,
          f"A9: doc/comment の分類 (doc {s.metrics.doc} / comment {s.metrics.comment})")

    # 10. b"" / c"" / br#""# が文字列として閉じる
    s = scan("selftest/a10.rs", 'fn f() {\n    let a = b"x";\n    let b = c"y";\n'
                                '    let c = br#"z"#;\n}\n')
    check(s.metrics.ncloc == 5 and s.metrics.comment == 0, "A10: byte/C/raw 文字列の扱い")

    # 11. 同名 fn を 2 つの impl に持つ入力 → key が分かれる
    s = scan("selftest/a11.rs", "impl A { fn new() {} }\nimpl B { fn new() {} }\n")
    check({f.key for f in s.fns} == {"selftest/a11.rs::A::new", "selftest/a11.rs::B::new"},
          f"A11: impl のスコープ ({[f.key for f in s.fns]})")

    # 12. 深い入れ子 + 内部の raw string (字下げされた WGSL) が max_indent を汚さない
    deep = "fn f() {\n"
    for d in range(1, 8):
        deep += " " * (4 * d) + f"let v{d} = {d};\n"
    deep += '    let s = r#"\n' + " " * 60 + "// wgsl\n" + '"#;\n}\n'
    s = scan("selftest/a12.rs", deep)
    check(s.fns and s.fns[0].max_indent == 7,
          f"A12: max_indent が raw string に汚染された ({s.fns[0].max_indent if s.fns else None})")

    # 13. `arch-lint: allow-fn-nesting` を付けた深い関数は違反にしない
    allowed = "fn deep() { // arch-lint: allow-fn-nesting\n"
    for d in range(1, 9):
        allowed += " " * (4 * d) + f"let v{d} = {d};\n"
    allowed += "}\n"
    check(_lines_of(scan("selftest/a13.rs", allowed), "FN-NESTING") == [],
          "A13: allow-fn-nesting が効いていない")

    # 14. `#[cfg(test)] use foo::{a, b};` は `}` の直後の `;` まで
    s = scan("selftest/a14.rs", "#[cfg(test)]\nuse foo::{a, b};\nfn prod() {\n    let x = 1;\n}\n")
    check(s.metrics.test == 2 and s.metrics.ncloc == 3,
          f"A14: use の範囲 (test {s.metrics.test} / ncloc {s.metrics.ncloc})")

    # 15. `->` と `>>` で本体の開きを取り違えない
    s = scan("selftest/a15.rs",
             "fn f() -> bool {\n    true\n}\nfn g<T: Into<String>>(x: T) {\n    let _ = x;\n}\n")
    check({f.key for f in s.fns} == {"selftest/a15.rs::f", "selftest/a15.rs::g"},
          f"A15: 本体の開きを取り違えた ({[(f.key, f.ncloc) for f in s.fns]})")
    check(all(f.ncloc == 3 for f in s.fns), f"A15: ncloc ({[f.ncloc for f in s.fns]})")

    # 16. impl の外の自由関数はスコープ空
    s = scan("selftest/a16.rs", "pub fn draw() {}\n")
    check([f.key for f in s.fns] == ["selftest/a16.rs::draw"], "A16: 自由関数のキー")

    # 17. generics 付き impl は generics を飛ばした直後の識別子が型名 (text_input.rs:181 型)
    s = scan("selftest/a17.rs", "impl<'a, M: ?Sized + 'static> Ui<'a, M> {\n    pub fn f() {}\n}\n")
    check([f.key for f in s.fns] == ["selftest/a17.rs::Ui::f"],
          f"A17: generics 付き impl のキー ({[f.key for f in s.fns]})")

    # 18. 同一型への複数 trait impl (midi_import.rs:120,128 型)
    s = scan("selftest/a18.rs",
             "impl From<std::io::Error> for E { fn from() {} }\n"
             "impl From<midly::Error> for E { fn from() {} }\n")
    check({f.key for f in s.fns} == {"selftest/a18.rs::E[From<std::io::Error>]::from",
                                     "selftest/a18.rs::E[From<midly::Error>]::from"},
          f"A18: trait impl のキー ({[f.key for f in s.fns]})")
    check(_lines_of(s, "KEY-COLLISION") == [], "A18: trait 修飾で衝突が消えていない")

    # 19. cfg 対の mod (shmem.rs:32,170 型)
    s = scan("selftest/a19.rs",
             "#[cfg(windows)]\nmod imp { impl T { fn f() {} } }\n"
             "#[cfg(unix)]\nmod imp { impl T { fn f() {} } }\n")
    check({f.key for f in s.fns} == {"selftest/a19.rs::imp[cfg(windows)]::T::f",
                                     "selftest/a19.rs::imp[cfg(unix)]::T::f"},
          f"A19: cfg 付き mod のキー ({[f.key for f in s.fns]})")

    # 20. cfg(debug_assertions) 対 — どちらも production コード (main.rs:831,848 型)
    s = scan("selftest/a20.rs",
             "#[cfg(debug_assertions)]\nfn g() {}\n#[cfg(not(debug_assertions))]\nfn g() {}\n")
    check({f.key for f in s.fns} == {"selftest/a20.rs::g[cfg(debug_assertions)]",
                                     "selftest/a20.rs::g[cfg(not(debug_assertions))]"},
          f"A20: cfg 付き fn のキー ({[f.key for f in s.fns]})")
    check(s.metrics.test == 0, f"A20: debug_assertions を test 扱いにした ({s.metrics.test})")

    # 21. cfg 以外の属性はキーに入れない
    s = scan("selftest/a21.rs", "#[allow(clippy::too_many_lines)]\nfn h() {}\n")
    check([f.key for f in s.fns] == ["selftest/a21.rs::h"],
          f"A21: cfg 以外の属性がキーに入った ({[f.key for f in s.fns]})")

    # 22. 同じキーの関数が 2 本 → KEY-COLLISION を 1 本出す (#2 の連番で黙らせない)
    s = scan("selftest/a22.rs", "impl Foo { fn new() {} }\nimpl Foo { fn new() {} }\n")
    coll = _lines_of(s, "KEY-COLLISION")
    check(len(coll) == 1 and coll[0].endswith("key collision: selftest/a22.rs::Foo::new"),
          f"A22: KEY-COLLISION ({coll})")

    # 23. CRLF / 末尾改行なしの raw
    s = scan("selftest/a23.rs", "fn f() {\r\n    let x = 1;\r\n}\r\n")
    check(s.metrics.raw == 3 and s.metrics.ncloc == 3, f"A23: CRLF の raw ({s.metrics.raw})")
    s = scan("selftest/a23b.rs", "fn f() {}\nlet x = 1;")
    check(s.metrics.raw == 2, f"A23: 末尾改行なしの raw ({s.metrics.raw})")

    # 24. 先頭が生成マーカーのコメント → 生成物
    s = scan("selftest/a24.rs", "/* automatically generated by rust-bindgen 0.71.1 */\nfn f() {}\n")
    check(s.generated, "A24: 生成物として判定できていない")

    # 25. 先頭コメントが無く、コード中の文字列に `// @generated` (ara-sys/build.rs:47 型)
    s = scan("selftest/a25.rs",
             'fn main() {\n    b.raw_line("// @generated by cargo — do not edit by hand.");\n}\n')
    check(not s.generated, "A25: 文字列中の @generated を生成物と誤判定した")
    # 25b. **先頭コメントブロックの「外」にある本物のコメント**は生成マーカーにしない。
    #      これが無いと「ファイル中のどこかのコメントを見る」実装でも A25 が通ってしまい、
    #      §1.4 の「先頭の連続コメント/空行ブロックだけを見る」規則が pin されない。
    s = scan("selftest/a25b.rs",
             "fn main() {}\n// automatically generated by something\nfn other() {}\n")
    check(not s.generated, "A25b: 先頭ブロックの外のコメントを生成マーカーに数えた")
    # 25c. 先頭が空行 + 行コメントでもマーカーなら生成物 (先頭ブロックの定義の確認)
    s = scan("selftest/a25c.rs", "\n// @generated\n\nfn main() {}\n")
    check(s.generated, "A25c: 先頭ブロック内のマーカーを見落とした")

    # 26a. **`#[cfg(not(test))]` を test 扱いにしない。** `not(test)` は
    #      「テストビルド以外でだけコンパイルされる」= production コードなので、
    #      test 扱いにすると production が丸ごと budget から消えて緑になる。
    prod = "".join(f"    let v{k} = {k};\n" for k in range(20))
    s = scan("selftest/a26a.rs", "#[cfg(not(test))]\npub mod win {\n" + prod + "}\n")
    check(s.metrics.test == 0 and s.metrics.ncloc == 23,
          f"A26a: cfg(not(test)) を test 扱いにした (test {s.metrics.test} / ncloc {s.metrics.ncloc})")
    check(not _is_cfg_test("cfg(all(not(test),windows))"),
          "A26a: cfg(all(not(test),…)) を test 扱いにした")
    check(_is_cfg_test("cfg(all(test,not(windows)))"),
          "A26a: cfg(all(test,not(…))) を test 扱いにできていない")
    check(_is_cfg_test("cfg(any(test,debug_assertions))"),
          "A26a: cfg(any(test,…)) を test 扱いにできていない")

    # 26b. **item でないもの (enum variant / struct field) に付いた `#[cfg(test)]` で
    #      範囲が暴走しない。** 暴走するとファイル末尾までテスト扱いになり、
    #      そこから先の違反が全部消える (このリポジトリが最も警戒する false green)。
    s = scan("selftest/a26b.rs",
             "enum E {\n    A,\n    #[cfg(test)]\n    B,\n    C,\n}\n"
             "pub fn production() {\n    let x = 1;\n}\n")
    check(s.metrics.test == 2 and s.metrics.ncloc == 7,
          f"A26b: variant の cfg(test) 範囲が暴走した (test {s.metrics.test} / ncloc {s.metrics.ncloc})")
    check([f.key for f in s.fns] == ["selftest/a26b.rs::production"],
          f"A26b: 後続の production 関数が消えた ({[f.key for f in s.fns]})")
    # 26c. 囲みブロックの終わりでも打ち切る (`,` が無い最後の field)
    s = scan("selftest/a26c.rs",
             "struct S {\n    #[cfg(test)]\n    a: u32\n}\npub fn production() {\n    let x = 1;\n}\n")
    check([f.key for f in s.fns] == ["selftest/a26c.rs::production"],
          f"A26c: field の cfg(test) 範囲が暴走した ({[f.key for f in s.fns]})")
    # 26d. generics の `,` で item を切らない (`fn f<A, B>()`)
    s = scan("selftest/a26d.rs",
             "#[cfg(test)]\nfn t<A, B>() {\n    let x = 1;\n}\npub fn production() {}\n")
    check(s.metrics.test == 4 and [f.key for f in s.fns] == ["selftest/a26d.rs::production"],
          f"A26d: generics の , で範囲を切った (test {s.metrics.test})")

    # 26e. **属性の塊の先頭行から範囲が始まる** (`#[allow]` が `#[cfg(test)]` の上にある形)
    s = scan("selftest/a26e.rs",
             "#[allow(dead_code)]\n#[cfg(test)]\nfn t() {\n    let x = 1;\n}\nfn prod() {}\n")
    check(s.metrics.test == 5 and s.metrics.ncloc == 1,
          f"A26e: 塊の先頭属性行が範囲に入っていない (test {s.metrics.test} / ncloc {s.metrics.ncloc})")

    # 26f. **型位置の `impl Trait` は scope を作らない。** 作ると入れ子の fn のキーが
    #      `<rel>::Foo::inner` に化ける (= baseline のキーが黙って別物になる)。
    s = scan("selftest/a26f.rs",
             "pub fn outer(x: impl Foo) -> impl Bar {\n    fn inner() {}\n    x\n}\n")
    check({f.key for f in s.fns} == {"selftest/a26f.rs::outer", "selftest/a26f.rs::inner"},
          f"A26f: 型位置の impl が偽スコープを作った ({[f.key for f in s.fns]})")

    # 26g. **内部属性 (`#![…]`) を次の item に積まない。**
    s = scan("selftest/a26g.rs", "#![cfg(feature)]\npub fn f() {}\n")
    check([f.key for f in s.fns] == ["selftest/a26g.rs::f"],
          f"A26g: 内部属性がキーへ漏れた ({[f.key for f in s.fns]})")

    # 26h. **force_test / 統合テスト判定**。ここが壊れると 164 件の違反が全部消えて
    #      arch-lint は「OK」で exit 0 になる。
    s = scan("selftest/a26h.rs", "pub fn f() {\n    let x = 1;\n}\n", force_test=True)
    check(s.metrics.ncloc == 0 and s.metrics.test == s.metrics.raw and s.fns == [],
          f"A26h: force_test が効いていない ({s.metrics})")
    check(is_integration_test("tests/zz_selftest.rs"),
          "A26h: tests/ 直下 (親に Cargo.toml) を統合テストと判定できない")
    check(not is_integration_test("zz_no_such_crate/tests/x.rs"),
          "A26h: 親に Cargo.toml が無い tests/ を統合テストと判定した")
    check(not is_integration_test("common/src/model/tests.rs"),
          "A26h: tests.rs という名前だけで統合テスト扱いにした")

    # ---- (B) 肯定側 canary — emit_check が実際に違反を出すこと ------------------
    # 26/27. FILE-BUDGET の境界
    over = "".join(f"const A{k}: u32 = {k};\n" for k in range(FILE_NCLOC_BUDGET + 1))
    hits = _lines_of(scan("selftest/b26.rs", over), "FILE-BUDGET")
    check(len(hits) == 1 and hits[0].split()[2] == str(FILE_NCLOC_BUDGET + 1),
          f"B26: FILE-BUDGET が 1001 行で出ない ({hits})")
    exact = "".join(f"const A{k}: u32 = {k};\n" for k in range(FILE_NCLOC_BUDGET))
    check(_lines_of(scan("selftest/b27.rs", exact), "FILE-BUDGET") == [],
          "B27: FILE-BUDGET が境界 1000 で出てしまう")

    # 28/29. FN-BUDGET の境界
    def fn_of(ncloc: int) -> str:
        body = "".join(f"    let v{k} = {k};\n" for k in range(ncloc - 2))
        return f"fn f() {{\n{body}}}\n"
    hits = _lines_of(scan("selftest/b28.rs", fn_of(FN_NCLOC_BUDGET + 1)), "FN-BUDGET")
    check(len(hits) == 1 and hits[0].split()[2] == str(FN_NCLOC_BUDGET + 1),
          f"B28: FN-BUDGET が 301 行で出ない ({hits})")
    check(_lines_of(scan("selftest/b29.rs", fn_of(FN_NCLOC_BUDGET)), "FN-BUDGET") == [],
          "B29: FN-BUDGET が境界 300 で出てしまう")

    # 30/31. FN-NESTING の境界
    def nest_of(depth: int) -> str:
        body = "".join(" " * (4 * d) + f"let v{d} = {d};\n" for d in range(1, depth + 1))
        return f"fn f() {{\n{body}}}\n"
    hits = _lines_of(scan("selftest/b30.rs", nest_of(FN_INDENT_BUDGET + 1)), "FN-NESTING")
    check(len(hits) == 1 and hits[0].split()[2] == f"{FN_INDENT_BUDGET + 1}/2",
          f"B30: FN-NESTING の計測値 ({hits})")
    check(_lines_of(scan("selftest/b31.rs", nest_of(FN_INDENT_BUDGET)), "FN-NESTING") == [],
          "B31: FN-NESTING が境界 6 段で出てしまう")

    # 32. 解決できない `#[cfg(test)] mod X;`
    hits = _lines_of(scan("selftest/b32.rs", "#[cfg(test)]\nmod nonexistent_zzz;\n"),
                     "UNRESOLVED-MOD")
    check(len(hits) == 1, f"B32: UNRESOLVED-MOD ({hits})")

    # 33. 何も違反しない入力 → LOC-BUDGET-OK の 1 行だけ
    out33 = emit_check([scan("selftest/b33.rs", "fn f() {\n    let x = 1;\n}\n")])
    check(len(out33) == 1 and out33[0].startswith("LOC-BUDGET-OK "),
          f"B33: 完走マーカーだけにならない ({out33})")

    # 34. 属性行に付けた allow-fn-budget が効く (§3.8 の範囲が attr_line から始まる証明)
    marked = "#[inline] // arch-lint: allow-fn-budget\n" + fn_of(FN_NCLOC_BUDGET + 1)
    check(_lines_of(scan("selftest/b34.rs", marked), "FN-BUDGET") == [],
          "B34: 属性行の allow-fn-budget が効いていない")

    # ---- (C) --filter-comments -------------------------------------------------
    # **フィルタ本体 (filter_comments) を通す。** lex の分類だけを assert すると、
    # 落とす / 残すの向きが反転しても canary が緑のままになり、check 1/2/3/5/12 の
    # 違反が全部消えても誰も気付けない。合成ファイルは read の差し替えで与える。
    FIXTURE_FILES = {
        "selftest/c_raw.rs": 'fn f() {\n    let s = r#"\n// pool: HashMap<(u32, u32), Bogus>\n"#;\n}\n',
        "selftest/c_line.rs": "// pool: HashMap<(u32, u32), Bogus>\nlet x = 1;\n",
        "selftest/c_block.rs": "/*\npool: HashMap<(u32, u32), Bogus>\n*/\nlet x = 1;\n",
        "selftest/c_trail.rs": "foo(); // x\n",
    }

    def fake_read(path: str) -> str:
        if path in FIXTURE_FILES:
            return FIXTURE_FILES[path]
        raise OSError(f"selftest: {path} は存在しません")

    def filt(rows: list[str]) -> list[str]:
        return list(filter_comments(rows, read=fake_read))

    # 35. raw string 中の行頭 `//` を指す行は **残る** (旧 strip_comments はここを落としていた)
    row35 = "selftest/c_raw.rs:3:// pool: HashMap<(u32, u32), Bogus>"
    check(filt([row35]) == [row35], "C35: raw string 中の行頭 // を落としてしまった")
    # 36. 本物の行頭コメント行を指す行は落ちる
    check(filt(["selftest/c_line.rs:1:// pool: HashMap<(u32, u32), Bogus>"]) == [],
          "C36: 本物の行頭コメント行を落とせない")
    # 37. `/* … */` の中の行を指す行は落ちる (旧実装は落とせていなかった)
    check(filt(["selftest/c_block.rs:2:pool: HashMap<(u32, u32), Bogus>"]) == [],
          "C37: ブロックコメント内の行を落とせない")
    # 38. 末尾コメント付きの実コード行を指す行は残る
    row38 = "selftest/c_trail.rs:1:foo(); // x"
    check(filt([row38]) == [row38], "C38: 末尾コメント付きの実コード行を落としてしまった")
    # 38b. 範囲外の行番号は落とさずに残す
    row38b = "selftest/c_trail.rs:99:foo();"
    check(filt([row38b]) == [row38b], "C38b: 範囲外の行番号を落としてしまった")
    # 39. 存在しない path は残す (read が OSError を投げる経路)
    row39 = "selftest/does_not_exist.rs:1:    pool: HashMap<(u32, u32), Bogus>,"
    check(filt([row39]) == [row39], "C39: 読めない path の行を落としてしまった")
    # 40. path:line:content の形をしていない行はそのまま素通し
    check(filt(["arch-lint: [NOTE] 何か", "not a row"]) == ["arch-lint: [NOTE] 何か", "not a row"],
          "C40: 形の違う行を素通しできていない")

    # ---- (D) 走査の下限 --------------------------------------------------------
    # 41. 走査が下限を割ったら緑にせず落ちる
    try:
        load_repo(files=[])
        check(False, "D41: 走査 0 件でも例外にならない")
    except LocBudgetError:
        check(True, "")
    # 42. git が起動できない / 非ゼロ終了なら空リストへ縮退しない
    try:
        scan_files(["git-does-not-exist-zzz", "ls-files"])
        check(False, "D42: git 不在で例外にならない")
    except LocBudgetError:
        check(True, "")
    try:
        scan_files(["git", "ls-files", "--this-option-does-not-exist-zzz"])
        check(False, "D42: git の非ゼロ終了で例外にならない")
    except LocBudgetError:
        check(True, "")

    if fails:
        print("loc-budget: self-test FAILED", file=sys.stderr)
        for f in fails:
            print(f"  - {f}", file=sys.stderr)
        return 1
    print(f"loc-budget: self-test ok (フィクスチャ {n_fixture} 件 / 保存則 {n_conserve} 件)")
    return 0


# ---------------------------------------------------------------- main


def main() -> int:
    ap = argparse.ArgumentParser(description="サイズ budget (不変条件 9) の測定器",
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    mode = ap.add_mutually_exclusive_group(required=True)
    mode.add_argument("--check", action="store_true", help="違反を stdout へ (arch_lint.sh が読む)")
    mode.add_argument("--report", action="store_true", help="上位ファイル / 関数の一覧")
    mode.add_argument("--self-test", action="store_true", help="判定器そのものの自己検査")
    mode.add_argument("--filter-comments", action="store_true",
                      help="stdin の path:line:content からコメント行を落とす")
    args = ap.parse_args()

    if args.self_test:
        return self_test()

    if args.filter_comments:
        try:
            sys.stdin.reconfigure(encoding="utf-8", errors="replace")
        except (AttributeError, ValueError):  # pragma: no cover
            pass
        for row in filter_comments(sys.stdin):
            print(row)
        return 0

    try:
        scans, generated = load_repo()
    except LocBudgetError as exc:
        print(f"loc-budget: [SELF-BROKEN] {exc}", file=sys.stderr)
        return 2

    try:
        if args.report:
            return report(scans, generated)
        for line in emit_check(scans, generated):
            print(line)
    except LocBudgetError as exc:
        print(f"loc-budget: [SELF-BROKEN] {exc}", file=sys.stderr)
        return 2
    return 0


if __name__ == "__main__":
    sys.exit(main())
