# Stop hook: detect patterns in current session metrics, write proposals to reflection_latest.md
# stdin: JSON from Claude Code (session_id, transcript_path, etc.)
# input log: %USERPROFILE%\.claude\projects\F--dev-daw-01\metrics\YYYY-MM.jsonl
# output: F:\dev\daw_01\docs\reflection_latest.md (last 5 entries kept)
# silent on failure (exit 0). All strings ASCII-only to avoid PS 5.1 encoding issues.

$ErrorActionPreference = 'SilentlyContinue'

$input_str = [Console]::In.ReadToEnd()
if (-not $input_str) { exit 0 }

try {
    $data = $input_str | ConvertFrom-Json
} catch {
    exit 0
}

$session_id = $data.session_id
if (-not $session_id) { exit 0 }

$logdir = Join-Path $env:USERPROFILE ".claude\projects\F--dev-daw-01\metrics"
$logfile = Join-Path $logdir "$(Get-Date -Format yyyy-MM).jsonl"
if (-not (Test-Path $logfile)) { exit 0 }

# Load entries for current session only
$entries = New-Object System.Collections.ArrayList
Get-Content $logfile -Encoding utf8 | ForEach-Object {
    if ($_) {
        try {
            $e = $_ | ConvertFrom-Json
            if ($e.session -eq $session_id) {
                [void]$entries.Add($e)
            }
        } catch {}
    }
}

if ($entries.Count -lt 3) { exit 0 }

# Pattern detection
$proposals = New-Object System.Collections.ArrayList
$bash  = @($entries | Where-Object { $_.tool -eq "Bash" -and $_.matcher })
$edits = @($entries | Where-Object { ($_.tool -eq "Edit" -or $_.tool -eq "Write") -and $_.matcher })
$reads = @($entries | Where-Object { $_.tool -eq "Read" -and $_.matcher })

# Pattern 1: same Bash command repeated 3+ in a row
for ($i = 0; $i -lt $bash.Count - 2; $i++) {
    if ($bash[$i].matcher -eq $bash[$i+1].matcher -and $bash[$i+1].matcher -eq $bash[$i+2].matcher) {
        $m = $bash[$i].matcher
        [void]$proposals.Add("Bash repeat: ``$m`` x3+ -> candidate for /slash command or skill")
        break
    }
}

# Pattern 2: Edit/Write same file 5+ times
if ($edits.Count -ge 5) {
    $top = ($edits | Group-Object matcher | Sort-Object Count -Descending)[0]
    if ($top.Count -ge 5) {
        [void]$proposals.Add("Edit hotspot: ``$($top.Name)`` x$($top.Count) -> candidate for focused hook or skill")
    }
}

# Pattern 3: 2+ consecutive Bash failures
$err_streak = 0
foreach ($b in $bash) {
    if ($b.status -eq "error") {
        $err_streak++
        if ($err_streak -ge 2) {
            [void]$proposals.Add("Bash repeated failure: ``$($b.matcher)`` -> candidate for debug skill or env check")
            break
        }
    } else {
        $err_streak = 0
    }
}

# Pattern 4: Read same file 5+ times
if ($reads.Count -ge 5) {
    $top = ($reads | Group-Object matcher | Sort-Object Count -Descending)[0]
    if ($top.Count -ge 5) {
        [void]$proposals.Add("Read hotspot: ``$($top.Name)`` x$($top.Count) -> candidate for memory entry or CLAUDE.md addition")
    }
}

if ($proposals.Count -eq 0) { exit 0 }

# Update reflection_latest.md (keep last 5 entries, newest first)
$reflfile = "F:\dev\daw_01\docs\reflection_latest.md"
$ts = Get-Date -Format "yyyy-MM-dd HH:mm"
$session_short = $session_id.Substring(0, [Math]::Min(8, $session_id.Length))

$new_block = New-Object System.Collections.ArrayList
[void]$new_block.Add("## $ts (session: $session_short)")
[void]$new_block.Add("")
foreach ($p in $proposals) { [void]$new_block.Add("- $p") }
[void]$new_block.Add("")
[void]$new_block.Add("metrics: $($entries.Count) tool calls (Bash:$($bash.Count) / Edit-Write:$($edits.Count) / Read:$($reads.Count))")
[void]$new_block.Add("")
[void]$new_block.Add("---")
[void]$new_block.Add("")

$header_lines = @(
    "# reflection_latest.md",
    "",
    "Auto-generated by Stop hook (``scripts/reflect.ps1``). Last 5 entries kept, newest first.",
    "Read at session start before working (see CLAUDE.md).",
    "",
    "---",
    ""
)

# Strip existing header to get body
$existing_body = ""
if (Test-Path $reflfile) {
    $raw = Get-Content $reflfile -Encoding utf8 -Raw
    $sep_match = [regex]::Match($raw, "(?ms)^---\s*$")
    if ($sep_match.Success) {
        $existing_body = $raw.Substring($sep_match.Index + $sep_match.Length).TrimStart("`r","`n")
    }
}

$combined = ($new_block -join "`n") + $existing_body

# Truncate if more than 5 entries
$session_headers = [regex]::Matches($combined, '(?m)^## \d{4}-\d{2}-\d{2}')
if ($session_headers.Count -gt 5) {
    $cut = $session_headers[5].Index
    $combined = $combined.Substring(0, $cut).TrimEnd() + "`n"
}

$final = ($header_lines -join "`n") + $combined
Set-Content -Path $reflfile -Value $final -Encoding utf8

exit 0
