[package]
name = "daw_plugin_host"
version.workspace = true
edition.workspace = true

[dependencies]
common = { path = "../common" }
ara-sys = { path = "../ara-sys" }
anyhow.workspace = true
arc-swap.workspace = true
reqwest.workspace = true
serde_json.workspace = true
bincode.workspace = true
clap-sys.workspace = true
com-scrape-types.workspace = true
hound.workspace = true
libloading.workspace = true
tokio.workspace = true
tracing.workspace = true
vst3.workspace = true

[target.'cfg(windows)'.dependencies]
windows.workspace = true

[dev-dependencies]
tempfile.workspace = true
