[package]
name = "daw_plugin_host"
version.workspace = true
edition.workspace = true

[dependencies]
common = { path = "../common" }
anyhow.workspace = true
arc-swap.workspace = true
clap-sys.workspace = true
libloading.workspace = true
tokio.workspace = true
tracing.workspace = true

[target.'cfg(windows)'.dependencies]
windows.workspace = true
